// app/layout.tsx
import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"

import { ClerkProvider } from '@clerk/nextjs'
import { Container } from "@/components/ui/atoms/Container"
import { ToastContainer } from "@/components/ui/molecules/Toast"
import { ThemeProvider } from '@/components/ui/layout/ThemeProvider'
import { StripeWrapper } from '@/components/ui/payments/StripeWrapper';

const inter = Inter({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: 'TerraFarming',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider afterSignOutUrl="/">
      <html lang="en" suppressHydrationWarning>
        <body className={inter.className}>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <StripeWrapper>
              {children}
            </StripeWrapper>
            <ToastContainer />
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  )
}